// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrate.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KullaniciStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("TCNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("kullanicis");
                });

            modelBuilder.Entity("EntityLayer.Concrate.StajBilgi", b =>
                {
                    b.Property<int>("StajBilgiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StajBilgiID"));

                    b.Property<string>("AdUnvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alanı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Başlamatrh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Bitistrh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CmtDahil")
                        .HasColumnType("bit");

                    b.Property<bool>("Egitim")
                        .HasColumnType("bit");

                    b.Property<int>("FaksNo")
                        .HasColumnType("int");

                    b.Property<bool>("Kabul")
                        .HasColumnType("bit");

                    b.Property<int>("KabulGün")
                        .HasColumnType("int");

                    b.Property<bool>("KatkıPayıOnay")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Onay")
                        .HasColumnType("bit");

                    b.Property<string>("RedSebep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ResmiTatil")
                        .HasColumnType("bit");

                    b.Property<bool>("StajBilgiStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StajTürü")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelNo")
                        .HasColumnType("int");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StajBilgiID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("stajBilgis");
                });

            modelBuilder.Entity("EntityLayer.Concrate.StajBilgi", b =>
                {
                    b.HasOne("EntityLayer.Concrate.Kullanici", "kullanici")
                        .WithMany("StajBilgis")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("EntityLayer.Concrate.Kullanici", b =>
                {
                    b.Navigation("StajBilgis");
                });
#pragma warning restore 612, 618
        }
    }
}
